added test cases and code cleanup
1) added new test cases
2) ask for confirmation before running test
3) replace tab to 2 spaces
4) fixed minor issue that block redis-sentinel service to start after test run

diff --git a/services/nutcracker b/services/nutcracker
--- a/services/nutcracker
+++ b/services/nutcracker
@@ -38,61 +38,61 @@ ulimit -Sn 100000
 
 do_start()
 {
-    if [ -f $WATCH_PID_FILE ]; then
-      kill $(cat $WATCH_PID_FILE) 2> /dev/null
-      rm $WATCH_PID_FILE 2> /dev/null
-    fi
-    touch $PIDFILE
-    mkdir -p /var/run/nutcracker
-    chown $USER:$GROUP -R /var/run/nutcracker
-    chown $USER:$GROUP $CONFFILE
-    chmod 755 /var/run/nutcracker
+  if [ -f $WATCH_PID_FILE ]; then
+    kill $(cat $WATCH_PID_FILE) 2> /dev/null
+    rm $WATCH_PID_FILE 2> /dev/null
+  fi
+  touch $PIDFILE
+  mkdir -p /var/run/nutcracker
+  chown $USER:$GROUP -R /var/run/nutcracker
+  chown $USER:$GROUP $CONFFILE
+  chmod 755 /var/run/nutcracker
 
-    echo -n "Starting ${NAME}: "
-    start-stop-daemon --start --quiet -m --pidfile $PIDFILE --chuid $USER:$GROUP --exec $DAEMON -- \
-        $DAEMON_ARGS
-        case "$?" in
-            0|1) echo "STARTED." ;;
-            2) echo "FAILED." ;;
-        esac
-    test -e $FILE_TO_WATCH || (touch $FILE_TO_WATCH;chown $REDIS_USER:$REDIS_USER $FILE_TO_WATCH)
-    iwatch -c "cat $FILE_TO_WATCH > $CONFFILE; chown $USER:$GROUP $CONFFILE;service $NAME restart" $FILE_TO_WATCH &
-    echo $! > $WATCH_PID_FILE
+  echo -n "Starting ${NAME}: "
+  start-stop-daemon --start --quiet -m --pidfile $PIDFILE --chuid $USER:$GROUP --exec $DAEMON -- \
+    $DAEMON_ARGS
+    case "$?" in
+      0|1) echo "STARTED." ;;
+      2) echo "FAILED." ;;
+    esac
+  test -e $FILE_TO_WATCH || (touch $FILE_TO_WATCH;chown $REDIS_USER:$REDIS_USER $FILE_TO_WATCH)
+  iwatch -c "cat $FILE_TO_WATCH > $CONFFILE; chown $USER:$GROUP $CONFFILE;service $NAME restart" $FILE_TO_WATCH &
+  echo $! > $WATCH_PID_FILE
 }
 
 do_stop()
 {
-    if [ -f $WATCH_PID_FILE ]; then
-      kill $(cat $WATCH_PID_FILE) 2> /dev/null
-      rm $WATCH_PID_FILE 2> /dev/null
-    fi
-    echo -n "Stopping ${NAME}: "
-    start-stop-daemon --stop --quiet --pidfile $PIDFILE --exec $DAEMON || true
+  if [ -f $WATCH_PID_FILE ]; then
+    kill $(cat $WATCH_PID_FILE) 2> /dev/null
+    rm $WATCH_PID_FILE 2> /dev/null
+  fi
+  echo -n "Stopping ${NAME}: "
+  start-stop-daemon --stop --quiet --pidfile $PIDFILE --exec $DAEMON || true
 
-    case "$?" in
-        0|1) echo "STOPPED.";;
-        2) echo "FAILED." ;;
-    esac
+  case "$?" in
+    0|1) echo "STOPPED.";;
+    2) echo "FAILED." ;;
+  esac
 }
 
 case "$1" in
-    start)
-        do_start
+  start)
+    do_start
+  ;;
+  stop)
+    do_stop
+  ;;
+  status)
+    status_of_proc -p $PIDFILE "$DAEMON" nutcracker && exit 0 || exit $?
+  ;;
+  restart)
+    do_stop
+    do_start
+  ;;
+  *)
+    echo "Usage: $SCRIPTNAME {start|stop|status|restart}" >&2
+    exit 3
     ;;
-    stop)
-        do_stop
-    ;;
-    status)
-      status_of_proc -p $PIDFILE "$DAEMON" nutcracker && exit 0 || exit $?
-    ;;
-    restart)
-      do_stop
-      do_start
-    ;;
-    *)
-        echo "Usage: $SCRIPTNAME {start|stop|status|restart}" >&2
-        exit 3
-        ;;
 esac
 
 exit
diff --git a/services/redis_s2_2 b/services/redis_s2_2
--- a/services/redis_s2_2
+++ b/services/redis_s2_2
@@ -1,14 +1,14 @@
 #! /bin/sh
 ### BEGIN INIT INFO
-# Provides:		redis_s2_2
-# Required-Start:	$syslog $remote_fs
-# Required-Stop:	$syslog $remote_fs $redis_sentinel
-# Should-Start:		$local_fs
-# Should-Stop:		$local_fs
-# Default-Start:	2 3 4 5
-# Default-Stop:		0 1 6
-# Short-Description:	redis-server (redis_s2_2) - Persistent key-value db
-# Description:		redis-server (redis_s2_2) - Persistent key-value db
+# Provides:    redis_s2_2
+# Required-Start:  $syslog $remote_fs
+# Required-Stop:  $syslog $remote_fs $redis_sentinel
+# Should-Start:    $local_fs
+# Should-Stop:    $local_fs
+# Default-Start:  2 3 4 5
+# Default-Stop:    0 1 6
+# Short-Description:  redis-server (redis_s2_2) - Persistent key-value db
+# Description:    redis-server (redis_s2_2) - Persistent key-value db
 ### END INIT INFO
 
 
@@ -29,7 +29,7 @@ test -x $DAEMON || exit 0
 
 if [ -r /etc/default/$NAME ]
 then
-	. /etc/default/$NAME
+  . /etc/default/$NAME
 fi
 
 . /lib/lsb/init-functions
@@ -38,52 +38,52 @@ set -e
 
 case "$1" in
   start)
-	echo -n "Starting $DESC: "
-	mkdir -p $RUNDIR
-	touch $PIDFILE
-	chown redis:redis $RUNDIR $PIDFILE $CONFIG
-        [ -f $LOGFILE ] && chown redis:redis $LOGFILE
-        [ -f $RDB ] && chown redis:redis $RDB
-        [ -f $AOF ] && chown redis:redis $AOF
-	chmod 755 $RUNDIR
+  echo -n "Starting $DESC: "
+  mkdir -p $RUNDIR
+  touch $PIDFILE
+  chown redis:redis $RUNDIR $PIDFILE $CONFIG
+  [ -f $LOGFILE ] && chown redis:redis $LOGFILE
+  [ -f $RDB ] && chown redis:redis $RDB
+  [ -f $AOF ] && chown redis:redis $AOF
+  chmod 755 $RUNDIR
 
-	if [ -n "$ULIMIT" ]
-	then
-		ulimit -n $ULIMIT
-	fi
+  if [ -n "$ULIMIT" ]
+  then
+    ulimit -n $ULIMIT
+  fi
 
-	if start-stop-daemon --start --quiet --umask 007 --pidfile $PIDFILE --chuid redis:redis --exec $DAEMON -- $DAEMON_ARGS
-	then
-		echo "$NAME."
-	else
-		echo "failed"
-	fi
-	;;
+  if start-stop-daemon --start --quiet --umask 007 --pidfile $PIDFILE --chuid redis:redis --exec $DAEMON -- $DAEMON_ARGS
+  then
+    echo "$NAME."
+  else
+    echo "failed"
+  fi
+  ;;
   stop)
-	echo -n "Stopping $DESC: "
-	if start-stop-daemon --stop --retry forever/TERM/1 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
-	then
-		echo "$NAME."
-	else
-		echo "failed"
-	fi
-	rm -f $PIDFILE
-	sleep 1
-	;;
+  echo -n "Stopping $DESC: "
+  if start-stop-daemon --stop --retry forever/TERM/1 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
+  then
+    echo "$NAME."
+  else
+    echo "failed"
+  fi
+  rm -f $PIDFILE
+  sleep 1
+  ;;
 
   restart|force-reload)
-	${0} stop
-	${0} start
-	;;
+  ${0} stop
+  ${0} start
+  ;;
 
   status)
-	status_of_proc -p ${PIDFILE} ${DAEMON} ${NAME}
-	;;
+  status_of_proc -p ${PIDFILE} ${DAEMON} ${NAME}
+  ;;
 
   *)
-	echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
-	exit 1
-	;;
+  echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
+  exit 1
+  ;;
 esac
 
 exit 0
diff --git a/services/redis_sentinel b/services/redis_sentinel
--- a/services/redis_sentinel
+++ b/services/redis_sentinel
@@ -1,19 +1,19 @@
 #! /bin/sh
 ### BEGIN INIT INFO
-# Provides:		redis_sentinel
-# Required-Start:	$syslog $remote_fs $redis_s1_1 $redis_s1_2 $redis_s2_3 $redis_s2_1 $redis_s2_2 $redis_s2_3
-# Required-Stop:	$syslog $remote_fs
-# Should-Start:		$local_fs
-# Should-Stop:		$local_fs
-# Default-Start:	2 3 4 5
-# Default-Stop:		0 1 6
-# Short-Description:	redis-server (redis_sentinel) - Persistent key-value db
-# Description:		redis-server (redis_sentinel) - Persistent key-value db
+# Provides:    redis_sentinel
+# Required-Start:  $syslog $remote_fs $redis_s1_1 $redis_s1_2 $redis_s2_3 $redis_s2_1 $redis_s2_2 $redis_s2_3
+# Required-Stop:  $syslog $remote_fs
+# Should-Start:    $local_fs
+# Should-Stop:    $local_fs
+# Default-Start:  2 3 4 5
+# Default-Stop:    0 1 6
+# Short-Description:  redis_sentinel - Redis Cluster agent
+# Description:    redis_sentinel - Redis Cluster agent
 ### END INIT INFO
 
 
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-DAEMON=/usr/bin/redis-server
+DAEMON=/usr/bin/redis-sentinel
 CONFIG=/etc/redis/sentinel.conf
 DAEMON_ARGS="$CONFIG --sentinel"
 NAME=redis_sentinel
@@ -28,7 +28,7 @@ test -x $DAEMON || exit 0
 
 if [ -r /etc/default/$NAME ]
 then
-	. /etc/default/$NAME
+  . /etc/default/$NAME
 fi
 
 . /lib/lsb/init-functions
@@ -37,52 +37,51 @@ set -e
 
 case "$1" in
   start)
-	echo -n "Starting $DESC: "
-	mkdir -p $RUNDIR
-	touch $PIDFILE
-	chown redis:redis $RUNDIR $PIDFILE
-        [ -f $LOGFILE ] && chown redis:redis $LOGFILE
-	chmod 755 $RUNDIR
+  echo -n "Starting $DESC: "
+  mkdir -p $RUNDIR
+  touch $PIDFILE
+  chown redis:redis $RUNDIR $PIDFILE
+  [ -f $LOGFILE ] && chown redis:redis $LOGFILE
+  chmod 755 $RUNDIR
 
-	if [ -n "$ULIMIT" ]
-	then
-		ulimit -n $ULIMIT
-	fi
+  if [ -n "$ULIMIT" ]
+  then
+    ulimit -n $ULIMIT
+  fi
 
-    	test -e $FILE_TO_WATCH || (touch $FILE_TO_WATCH;chown redis:redis $FILE_TO_WATCH)
-        # Run as root as it require to restart another process
-	if start-stop-daemon --start --quiet --umask 007 --pidfile $PIDFILE --chuid redis:redis --exec $DAEMON -- $DAEMON_ARGS
-	then
-		echo "$NAME."
-	else
-		echo "failed"
-	fi
-	;;
+  test -e $FILE_TO_WATCH || (touch $FILE_TO_WATCH;chown redis:redis $FILE_TO_WATCH)
+  if start-stop-daemon --start --quiet --umask 007 --pidfile $PIDFILE --chuid redis:redis --exec $DAEMON -- $DAEMON_ARGS
+  then
+    echo "$NAME."
+  else
+    echo "failed"
+  fi
+  ;;
   stop)
-	echo -n "Stopping $DESC: "
-	if start-stop-daemon --stop --retry forever/TERM/1 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
-	then
-		echo "$NAME."
-	else
-		echo "failed"
-	fi
-	rm -f $PIDFILE
-	sleep 1
-	;;
+  echo -n "Stopping $DESC: "
+  if start-stop-daemon --stop --retry forever/TERM/1 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
+  then
+    echo "$NAME."
+  else
+    echo "failed"
+  fi
+  rm -f $PIDFILE
+  sleep 1
+  ;;
 
   restart|force-reload)
-	${0} stop
-	${0} start
-	;;
+  ${0} stop
+  ${0} start
+  ;;
 
   status)
-	status_of_proc -p ${PIDFILE} ${DAEMON} ${NAME}
-	;;
+  status_of_proc -p ${PIDFILE} ${DAEMON} ${NAME}
+  ;;
 
   *)
-	echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
-	exit 1
-	;;
+  echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
+  exit 1
+  ;;
 esac
 
 exit 0
